### ISSUE TITLE
Prod: Authentication: Facebook

### ISSUE THREAD

**Issue by Wholloran** [openforge/JuntoScope#153]
Unable to Authenticate with Facebook. When the native screen appears it displays the following Error for me (my FB account is set up as a developer account): 
> Invalid key hash. The key hash 680V7i2LjH763TNRoRalFMrH+Ql= does not match any stored key hashes. Configure your app key hashes at https://developers.facebook.com/apps/1427549454016328 <

For accounts that are not set up ad a developer account, they get the native popup and then are left with an infinite loading spinner.

Google pixel running 9.0 (pie)
Galaxy s7 running 8.0 (oreo)

**Comment by Wholloran** [comment]
I want to add more information to this ticket. I am seeing that if you have the Facebook application installed on the same device as JuntoScope, when you go to authenticate via FB in JS you will get the Hash key Error. However, if you uninstall/disable the facebook application, and then go to authenticate via FB in JS you will be able to successfully log in to the application. Note that this is v1.0.1 tested using google pixel, S8, and s7(let me know if you need version) using Geoff and my own Facebook account.

**Comment by Fdom92** [comment]
I built an app for production and tried to login with facebook and was able to do it.

**Comment by Wholloran** [comment]
FB auth works on prod, closing ticket
