### ISSUE TITLE
Unable to add a connection on Device (built from teamwork-auth branch)

### ISSUE THREAD

**Issue by Wholloran** [openforge/JuntoScope#159]
When attempting to add a connection to an account from a device that was built from the Teamwork-auth branch I am given the following error. (see screenshot below)

Steps to recreate:
1. login to a device
2. add connection
3. enter valid Teamwork credentials
4. Error is displayed
Tested with build from teamwork-auth branch on a google pixel

![screenshot_20180919-113123](https://user-images.githubusercontent.com/37937571/45763984-ad19bd80-bbff-11e8-96a3-16ec653110de.png)

**Comment by daftclaud** [comment]
This issue was caused by a missing Android manifest file. Note that the person that is in charge of building must manually maintain the AndroidManifest.xml file since it is not tracked by github.

**Comment by Wholloran** [comment]
Able to add connection  now, closing ticket
