### ISSUE TITLE
Uncomplete README: Missing const values in environment.ts

### ISSUE THREAD

**Issue by ionic4-toolbox** [openforge/JuntoScope#178]
Just follow your README.md to create config/config.ts:

```
export const FIREBASE_CONFIG = {
  apiKey: "",
  authDomain: "",
  databaseURL: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: ""
}
```

But when i start ionic serve, i've got an error abut missing export members:
```
  FIREBASE_DEV_CONFIG
  FIREBASE_DEV_FUNCTIONS
  GOOGLE_WEB_CLIENT_ID_DEV
```

**Comment by PaulPaulDevelops** [comment]
Hey @ionic4-toolbox !

Thank you for checking out the repository. I apologize for the delay of our response. We are scheduling in for next week for one of our team members to update the README.md with the correct instructions so you are able to run the project with your own credentials.

If you have any further questions in the mean time feel free to open up another issue or let me know!

Thanks.

**Comment by PaulPaulDevelops** [comment]
Hey @ionic4-toolbox !

We updated our README.md today with updated instructions per your issue. Please check it out and let us know if you have any more questions.

I'll close this issue for right now, but feel free to create a new one if you find or have questions about anything.
