### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by Wholloran** [openforge/JuntoScope#76]
- Cache: when logging in with an account, if I log out and attempt to log in via another account(same platform (fb/google/twitter) it will log me right in with the same account rather then allowing me to enter different account details

Steps to recreate:
1. log in via google
2. log out
3. Log in via google using a different account
you will be logged right in and not allowed to pick a different account

v1.0.0 only on devices, not emulated

**Comment by Wholloran** [comment]
The following still appears to be caching:
iOS: Twitter and FB
Android: Fb

**Comment by Fdom92** [comment]
The only one plugin that don't allow us to change to another account after log in with an account is Facebook plugin (seems to be open issues https://github.com/jeduan/cordova-plugin-facebook4/issues/591), the other ones, Twitter and Google, you can switch to another account after logout.

**Comment by Wholloran** [comment]
Albe to select accounts on Twitter and Google, closing ticket

**Comment by lucasnguyen3979** [comment]
> Albe to select accounts on Twitter and Google, closing ticket

How about Facebook my friend?
