### ISSUE TITLE
Style Changes:

### ISSUE THREAD

**Issue by Wholloran** [openforge/JuntoScope#90]
Changes for the Design/flow:

Swap styles for the buttons:
-  Have the options for the moderator to click be white and then turn orange on the selection
- have participants entries be white by default rather than orange

Langage changes:
- Change the Results language to "Results: (section one) or something along those lines the indicated actions
- Change language on 4.0k button from "Submit" to "Continue"

**Comment by Wholloran** [comment]
So the options for the moderator to click will turn the button orange on press but it doesn't stay that color. I believe it should stay highlighted to indicate what the current selection is.

**Comment by PaulPaulDevelops** [comment]
Almost there. I'll try to resolve this.

**Comment by Wholloran** [comment]
styles have been updated to match the above requirements, closing ticket
